name: Create Release Branch and PR

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-release-branch-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu || true

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Determine next version
        id: next-version
        run: |
          next_version=$(npx release-it --release-version)
          echo "Next version: $next_version"
          echo "version=$next_version" >> $GITHUB_OUTPUT

      - name: Create and checkout release branch
        run: |
          git checkout -b release-v${{ steps.next-version.outputs.version }}

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release -- --ci --preRelease --no-git.requireUpstream --no-git.push --no-npm.publish --no-github.release

      - name: Push changes and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -u origin release-v${{ steps.next-version.outputs.version }}
          pr_url=$(gh pr create --title "Release v${{ steps.next-version.outputs.version }}" --body "This PR prepares the release for version ${{ steps.next-version.outputs.version }}. Please review and merge to trigger the release process." --base main --head release-v${{ steps.next-version.outputs.version }})
          echo "Created PR: $pr_url"