name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  HUSKY: 0

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Extract version from branch name
        id: get_version
        run: echo "VERSION=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/release-v//')" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Extract latest changes
        run: |
          sed -n "/## \[${{ steps.get_version.outputs.VERSION }}/,/## \[/p" CHANGELOG.md | sed '$d' > RELEASE_NOTES.md

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh release create v${{ steps.get_version.outputs.VERSION }} \
            --title "Release v${{ steps.get_version.outputs.VERSION }}" \
            --notes-file RELEASE_NOTES.md